JSON validation support in CI
Most of the openbmc repositories depend on json configuration files ,
which are consumed by the respective daemons at runtime.

Its a good value add to catch the json validation errors early in the
repository CI itself.

TestedBy :
1. Bad JSON testing :

Running the json validator on the commit >>
checking : configurations/events/stateSensorPdrs.json
checking : configurations/fru_master.json
checking : configurations/host/dbus_to_host_effecter.json
checking : configurations/host/host_frus.json
checking : configurations/pdr/11.json
checking : configurations/pdr/4.json
checking : host-bmc/test/host_effecter_jsons/good/dbus_to_host_effecter.json
checking : host-bmc/test/host_effecter_jsons/malformed/dbus_to_host_effecter.json
Error: Parse error on line 1:
"effecters": [    {        "d
-----------^
Expecting 'EOF', '}', ',', ']', got ':'

2. No JSON change testing
Running spelling check on Commit Message
openbmc-dictionary - misspelling count >>
0
generic-dictionary - misspelling count >>
0
Running the json validator on the commit >>
No json files in the commit
Formatting code under /home/manojeda/Downloads/phosphor-networkd/

3. Good JSON testing

Running spelling check on Commit Message
openbmc-dictionary - misspelling count >>
0
generic-dictionary - misspelling count >>
0
Running the json validator on the commit >>
checking : test.json
Formatting code under /home/lkammath/Downloads/phosphor-networkd/

Signed-off-by: Manojkiran Eda <manojkiran.eda@gmail.com>

Change-Id: I2c2c14b18bb626b1a5ab5d818b92d5ba370e1639
Signed-off-by: Manojkiran Eda <manojkiran.eda@gmail.com>