Update patch set 13
Patch Set 13:

> Patch Set 13:
> 
> > Patch Set 13:
> > 
> > This broke google-misc. Needs fixes for symlink loops.
> > 
> > ```
> > Formatting code under /src/google-misc/
> > Running the json validator on the repo using the global config >
> > eslint /src/google-misc --no-eslintrc -c /src/eslint-global-config.json                --ext .json --resolve-plugins-relative-to /usr/local/lib/node_modules               --no-error-on-unmatched-pattern
> > 
> > Oops! Something went wrong! :(
> > 
> > ESLint: 8.0.1
> > 
> > Error: ELOOP: too many symbolic links encountered, stat '/src/google-misc/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects'
> > ```
> 
> I believe , this is a legitimate issue that should be fixed in the google-misc repo itself.

If that's your opinion, feel free to propose a patchset, but circular symlinks are allowed in the filesystem, and something that should be handled by any CI solution we use.

> 
> google-misc/acpi-power-state-daemon on  master is 📦 v0.1
> 🌞 ⚡  cd subprojects
> google-misc/acpi-power-state-daemon/subprojects on  master
> 🌞 ⚡  ls
> acpi-power-state-daemon  fmt.wrap  googletest.wrap  libcr51sign  metrics-ipmi-blobs  ncsid  nemora-postd  phosphor-dbus-interfaces.wrap  phosphor-logging.wrap  sdbusplus.wrap  stdplus.wrap
> google-misc/acpi-power-state-daemon/subprojects on  master
> 🌞 ⚡  cd acpi-power-state-daemon/
> google-misc/acpi-power-state-daemon/subprojects/acpi-power-state-daemon on  master is 📦 v0.1
> 🌞 ⚡  ls
> acpi-power-state.service.in  acpi_power_state.cpp  host-s0-state.target  host-s5-state.target  meson.build  subprojects
> google-misc/acpi-power-state-daemon/subprojects/acpi-power-state-daemon on  master is 📦 v0.1
> 🌞 ⚡  cd subprojects
> google-misc/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects on  master
> 🌞 ⚡  ls
> acpi-power-state-daemon  fmt.wrap  googletest.wrap  libcr51sign  metrics-ipmi-blobs  ncsid  nemora-postd  phosphor-dbus-interfaces.wrap  phosphor-logging.wrap  sdbusplus.wrap  stdplus.wrap
> google-misc/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects on  master
> 🌞 ⚡  cd acpi-power-state-daemon/
> google-misc/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon on  master is 📦 v0.1
> 🌞 ⚡  ls
> acpi-power-state.service.in  acpi_power_state.cpp  host-s0-state.target  host-s5-state.target  meson.build  subprojects
> google-misc/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon on  master is 📦 v0.1
> 
> Its a recursive loop of symlinks ..and once a call goes in ..it never comes out.

Somehow the other CI scripts don't seem to have an issue with that, I suspect because they're using git ls-files to get the file list, should Ci build scripts be doing the same thing?

Patch-set: 13