remove cppcheck
The output is ignored anyways, it prints very verbose logs, which no one
seems to have fixed in a very long time, and we don't really need it
since clang-tidy already performs the static analysis.

For example we have [1], [2] in which cppcheck prints 'error' messages
which are not even applicable, like

```
/usr/local/include/boost/cstdint.hpp:229:0: error: #error defaults not correct; you must hand modify boost/cstdint.hpp [preprocessorErrorDirective]
```

or

```
/usr/local/include/gtest/gtest-matchers.h:718:12: error: Reference to local variable returned. [returnReference]
    return v;
```

because the error was found in a file from the subproject. It is then
promptly ignored together with all the other warnings and errors from
cppcheck and both mentioned CI runs are successful.

References:

[1] https://jenkins.openbmc.org/job/ci-repository/107325/console
[2] https://jenkins.openbmc.org/job/ci-repository/107269/console

Change-Id: Ic789800976cc9d5de0eb6d13a25d368a08869052
Signed-off-by: Alexander Hansen <alexander.hansen@9elements.com>