build-setup: support podman
We have some Redhat servers I'm interested in using for OpenBMC builds.
With just the minor change in this commit, I was able to get openbmc to
successfully build on a RH8 system which points "docker" to the podman
executable.

The failure without this commit is the following:
```
Error: runc: runc create failed: unable to start container process: exec: "/home/geissonator/89239843/build.sh": stat /home/geissonator/89239843/build.sh: permission denied: OCI permission denied
```

Some online searching brought me to this --userns parameter. It fixed my
issues on the RH8 system but unfortunately it is not compatible with the
real docker comman line tool. Hence the need to check for podman in this
commit.

Tested:
- Confirmed openbmc will build on RH8 system with podman
- Confirmed openbmc still builds on Ubuntu system

Change-Id: I3d1127c25dd08a1c8748943f8f3a1add11fe12ee
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>