Update patch set 13
Patch Set 13:

This broke google-misc. Needs fixes for symlink loops.

```
Formatting code under /src/google-misc/
Running the json validator on the repo using the global config >
eslint /src/google-misc --no-eslintrc -c /src/eslint-global-config.json                --ext .json --resolve-plugins-relative-to /usr/local/lib/node_modules               --no-error-on-unmatched-pattern

Oops! Something went wrong! :(

ESLint: 8.0.1

Error: ELOOP: too many symbolic links encountered, stat '/src/google-misc/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects/acpi-power-state-daemon/subprojects'
```

Patch-set: 13
CC: Gerrit User 1000188 <1000188@adbd0a64-1f21-4d83-b585-671fe73cb6e4>