unit-test: add meson version check for C++23
We can start using C++23 in Meson, but it requires meson 1.1.1 or
later.  Add the meson_version check in unit-test just like we've
done in the past for C++20.

Tested:

Changed sdbusplus to only have 'cpp_std=c++23' while using older
meson_version and experienced the expected exception.

```
Exception: C++23 support requires specifying in meson.build: meson_version: '>=1.1.1'
```

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I3d355f5176fb1874b7301ab995e96f22dbd6b429