build-qemu-robot-docker: upgrade to focal
The 'pip' version that comes with bionic is no longer able to
install some of the python modules we need.  Specificially, we
end up with a failure as:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lz9dedw0/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

Rather than pin the cryptography module, which is actually a
dependency from a few levels down, upgrade the distro to focal to
pick up a new version of pip.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ief9aaccbe14b835a2dcae5c7d53cc5969f044cf3