Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> ImportError: cannot import name 'FeatureDeprecated' from partially initialized module 'mesonbuild.interpreterbase' (most likely due to a circular import) (/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase.py)

Looks like these are being caused by something to do with this:

scripts/unit-test.py:from mesonbuild import coredata, optinterpreter
scripts/unit-test.py:from mesonbuild.mesonlib import OptionKey
scripts/unit-test.py:from mesonbuild.mesonlib import version_compare as meson_version_compare

Patch-set: 1
Reviewer: Gerrit User 1000000 <1000000@adbd0a64-1f21-4d83-b585-671fe73cb6e4>