Enforce commit message style
Throughout the project, it is a manual human process to enforce the idea
of commit message formatting, and leads to more conflict than would
ideally be required for something that's relatively algorithmic, and
able to be enforced by CI.  Jenkins is able to give faster response
times to users, thus ensuring that committers are more likely to be able
to resolve their commit message issues in a timely manner.

This commit adds the gitlint[1] application to our builds, and
integrates its checks with CI in the format-code.sh script.  Gitlint
appears to be a relatively active project with a number of releases,
relatively up to date commits on its github, and by the documentation as
well as this authors testing, appears to do exactly what the project
needs in terms of checks.

gitlint has a number of configuration options[2], of which the defaults
appear to be ok for OpenBMCs style requirements. This commit checks in a
.gitlint file that was generated via 'gitlint generate-config' to use as
a starting point.

To avoid impacting the entire project at this time, this commit checks
for the existence of a .openbmc-enforce-gitlint file in the root of the
directory, and uses that to gate its scanning.  At some point in the
future, once we've determined this meets our needs, this check will be
removed so that we can enforce this project-wide.

Gitlint also supports user-defined rules[3], so it seems likely that in
the future, we could also support our requirements for the "Tested"
field, but that is not included in this commit.

Tested:
Created a commit with a title that was too long, as well as added a
.gitlint file in bmcweb.  Ran openbmc-build-scripts and observed.

'''
Running spelling check on Commit Message
openbmc-dictionary - misspelling count >>
0
generic-dictionary - misspelling count >>
0
1: T1 Title exceeds max length (62>50): "my very long commit message that is way too long for this line"
Traceback (most recent call last):
  File "/build/unit-test.py", line 1229, in <module>
    check_call_cmd(f, CODE_SCAN_DIR)
  File "/build/unit-test.py", line 234, in check_call_cmd
    check_call(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/build/format-code.sh', '/build/bmcweb')' returned non-zero exit status 1.
'''

[1] https://jorisroovers.com/gitlint/
[2] https://jorisroovers.com/gitlint/configuration/
[3] https://jorisroovers.com/gitlint/user_defined_rules/

Signed-off-by: Ed Tanous <edtanous@google.com>
Change-Id: If42a22bfeca223fd5bc8f35ed937aa5f60713f2a